# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160721154500 on 2016-07-22 09:30
from __future__ import unicode_literals

import avatar.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=avatar.models.AvatarField(),
        ),
    ]
